import { mutation } from "./_generated/server";
import { v } from "convex/values";

// SHA-256 password hash — reused from auth.ts pattern
async function hashPassword(password: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(password);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}

// All 16 ladies — seeded as professional users (password: "dodo123")
const PROFESSIONALS = [
  {
    slug: "amara",
    name: "Amara Okonkwo",
    title: "Master Hair Stylist & Braiding Specialist",
    avatar: "/girls/1763046071553edited-image.webp",
    coverImage: "/girls/1770314038130edited-image.webp",
    bio: "With over 12 years of experience in natural hair care and protective styling, I specialize in braids, locs, twists, and all-natural hair treatments. I believe every woman deserves to feel beautiful and confident in her natural hair.",
    category: "companions",
    skills: ["Braiding", "Natural Hair Care", "Locs", "Hair Coloring", "Protective Styles"],
    location: "Kissy",
    ethnicity: "African",
    rating: 4.9,
    reviewCount: 156,
    yearsExperience: 12,
    availability: "Mon-Sat, 9AM-6PM",
    languages: ["English", "Yoruba", "Igbo"],
    verified: true,
    age: 25,
    bodyType: "Average",
    interests: ["Swimming", "Music", "Travel", "Hiking", "Beach", "Gaming"],
    isOnline: true,
    isLive: false,
    services: [
      { name: "Box Braids", description: "Classic box braids in various sizes", price: 150, duration: "4-6 hours" },
      { name: "Knotless Braids", description: "Pain-free knotless braiding technique", price: 200, duration: "5-7 hours" },
      { name: "Loc Maintenance", description: "Retwisting and styling for locs", price: 80, duration: "2-3 hours" },
      { name: "Natural Hair Treatment", description: "Deep conditioning and hair health treatment", price: 60, duration: "1.5 hours" },
    ],
    portfolio: [
      { imageUrl: "/girls/1763046071553edited-image.webp", title: "Bohemian Locs", description: "Goddess locs with curly ends" },
      { imageUrl: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", title: "Knotless Braids", description: "Medium knotless braids" },
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "Natural Twist Out", description: "Defined twist out style" },
    ],
    reviews: [
      { reviewerName: "Sarah M.", reviewerAvatar: "/girls/1770314038130edited-image.webp", rating: 5, comment: "Amara is absolutely amazing! My braids lasted 8 weeks and looked fresh the entire time.", reviewedAt: "2024-01-15" },
      { reviewerName: "Chioma A.", reviewerAvatar: "/girls/1774305302779edited-image.webp", rating: 5, comment: "Best braider in Lagos! She's gentle, fast, and the results are always stunning.", reviewedAt: "2024-01-10" },
    ],
  },
  {
    slug: "priya",
    name: "Dr. Priya Sharma",
    title: "Certified Nutritionist & Wellness Coach",
    avatar: "/girls/1774305302779edited-image.webp",
    coverImage: "/girls/1770314038130edited-image.webp",
    bio: "As a certified nutritionist with a PhD in Clinical Nutrition, I help women achieve their health goals through personalized meal plans and lifestyle coaching. My holistic approach combines traditional Ayurvedic wisdom with modern nutritional science.",
    category: "wellness",
    skills: ["Nutrition Planning", "Weight Management", "Ayurveda", "Sports Nutrition", "Gut Health"],
    location: "Freetown",
    ethnicity: "West African",
    rating: 4.8,
    reviewCount: 89,
    yearsExperience: 8,
    availability: "Mon-Fri, 10AM-7PM",
    languages: ["English", "Hindi", "Marathi"],
    verified: true,
    age: 21,
    bodyType: "Curvy",
    interests: ["Photography", "Fitness", "Yoga", "Shopping"],
    isOnline: false,
    isLive: false,
    services: [
      { name: "Initial Consultation", description: "Comprehensive health assessment and goal setting", price: 120, duration: "1.5 hours" },
      { name: "Monthly Meal Plan", description: "Customized 4-week meal plan with recipes", price: 200, duration: "Ongoing" },
      { name: "Weekly Coaching", description: "Weekly check-ins and plan adjustments", price: 80, duration: "30 mins" },
      { name: "Gut Health Program", description: "8-week gut restoration program", price: 450, duration: "8 weeks" },
    ],
    portfolio: [
      { imageUrl: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", title: "Balanced Meals", description: "Sample client meal prep" },
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "Wellness Workshop", description: "Community nutrition event" },
    ],
    reviews: [
      { reviewerName: "Jennifer L.", reviewerAvatar: "/girls/1774305302779edited-image.webp", rating: 5, comment: "Dr. Sharma completely transformed my relationship with food. I lost 15kg and feel amazing!", reviewedAt: "2024-01-20" },
    ],
  },
  {
    slug: "maya",
    name: "Maya Chen",
    title: "UX/UI Designer & Brand Strategist",
    avatar: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg",
    coverImage: "/girls/1763046071553edited-image.webp",
    bio: "I create beautiful, user-centered digital experiences that help businesses connect with their audiences. With a background in psychology and 7 years in design, I bring both creativity and strategic thinking to every project.",
    category: "content-creators",
    skills: ["UI Design", "UX Research", "Brand Identity", "Figma", "Prototyping"],
    location: "Freetown",
    ethnicity: "Sierra Leonean",
    rating: 4.9,
    reviewCount: 67,
    yearsExperience: 7,
    availability: "Mon-Fri, 9AM-5PM SGT",
    languages: ["English", "Mandarin", "Cantonese"],
    verified: true,
    age: 32,
    bodyType: "Petite",
    interests: ["Art", "Yoga", "Beach", "Travel"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Brand Identity Package", description: "Logo, colors, typography, and brand guidelines", price: 1500, duration: "2-3 weeks" },
      { name: "Website Design", description: "Complete website UI/UX design", price: 2500, duration: "3-4 weeks" },
      { name: "App Design", description: "Mobile app interface design", price: 3000, duration: "4-6 weeks" },
      { name: "Design Consultation", description: "1-hour design strategy session", price: 150, duration: "1 hour" },
    ],
    portfolio: [
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "E-commerce Redesign", description: "Fashion brand website" },
      { imageUrl: "/girls/1774305302779edited-image.webp", title: "Mobile Banking App", description: "Fintech app design" },
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Brand Identity", description: "Startup branding project" },
    ],
    reviews: [
      { reviewerName: "David K.", reviewerAvatar: "/girls/1775215902622edited-image.webp", rating: 5, comment: "Maya delivered exceptional work. Our conversion rate increased by 40% after the redesign!", reviewedAt: "2024-01-18" },
    ],
  },
  {
    slug: "isabella",
    name: "Isabella Rodriguez",
    title: "Professional Chef & Event Caterer",
    avatar: "/girls/1763046071553edited-image.webp",
    coverImage: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg",
    bio: "Bringing authentic Latin American flavors to your table! I specialize in private dining experiences, event catering, and cooking classes. Every dish tells a story of my Colombian heritage combined with modern culinary techniques.",
    category: "entertainers",
    skills: ["Latin Cuisine", "Event Catering", "Private Chef", "Cooking Classes", "Meal Prep"],
    location: "Pujehun",
    ethnicity: "West African",
    rating: 4.7,
    reviewCount: 134,
    yearsExperience: 10,
    availability: "Tue-Sun, Flexible hours",
    languages: ["English", "Spanish"],
    verified: true,
    age: 30,
    bodyType: "Slim",
    interests: ["Nightlife", "Travel", "Beach", "Gaming", "Movies"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Private Dinner Party", description: "Full-service dinner for up to 10 guests", price: 500, duration: "4-5 hours" },
      { name: "Weekly Meal Prep", description: "5 days of prepared meals", price: 300, duration: "Half day" },
      { name: "Cooking Class", description: "Hands-on Latin cooking class for 4-8 people", price: 200, duration: "3 hours" },
      { name: "Event Catering", description: "Per person pricing for events 20+", price: 45, duration: "Per person" },
    ],
    portfolio: [
      { imageUrl: "/girls/1774305302779edited-image.webp", title: "Private Dinner", description: "Intimate dinner party setup" },
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Catering Spread", description: "Corporate event catering" },
      { imageUrl: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", title: "Signature Dishes", description: "Colombian fusion cuisine" },
    ],
    reviews: [
      { reviewerName: "Michelle T.", reviewerAvatar: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", rating: 5, comment: "Isabella catered our wedding and guests are still talking about the food months later!", reviewedAt: "2024-01-12" },
    ],
  },
  {
    slug: "fatima",
    name: "Fatima Al-Hassan",
    title: "Business Consultant & Financial Advisor",
    avatar: "/girls/1775215902622edited-image.webp",
    coverImage: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp",
    bio: "Empowering women entrepreneurs to build sustainable, profitable businesses. With 15 years in corporate finance and business strategy, I provide practical guidance on financial planning, business development, and strategic growth.",
    category: "escorts",
    skills: ["Business Strategy", "Financial Planning", "Startup Consulting", "Investment Advice", "Business Plans"],
    location: "Juba Hill",
    ethnicity: "Sierra Leonean",
    rating: 4.9,
    reviewCount: 78,
    yearsExperience: 15,
    availability: "Sun-Thu, 9AM-6PM GST",
    languages: ["English", "Arabic", "French"],
    verified: true,
    age: 32,
    bodyType: "Athletic",
    interests: ["Beach", "Art", "Photography"],
    isOnline: true,
    isLive: false,
    services: [
      { name: "Business Strategy Session", description: "2-hour deep dive into your business", price: 350, duration: "2 hours" },
      { name: "Financial Health Check", description: "Complete business financial analysis", price: 500, duration: "1 week" },
      { name: "Monthly Retainer", description: "Ongoing advisory and support", price: 1200, duration: "Monthly" },
      { name: "Business Plan Development", description: "Investor-ready business plan", price: 2000, duration: "2-3 weeks" },
    ],
    portfolio: [
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Client Success", description: "Startup grew 300% in 1 year" },
      { imageUrl: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", title: "Workshop", description: "Women in Business seminar" },
    ],
    reviews: [
      { reviewerName: "Aisha N.", reviewerAvatar: "/girls/1763046071553edited-image.webp", rating: 5, comment: "Fatima helped me secure my first round of funding. Her expertise is invaluable!", reviewedAt: "2024-01-22" },
    ],
  },
  {
    slug: "nneka",
    name: "Nneka Adeyemi",
    title: "Full-Stack Developer & Tech Educator",
    avatar: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp",
    coverImage: "/girls/1770314038130edited-image.webp",
    bio: "Building digital solutions and empowering the next generation of women in tech. I specialize in web development, mobile apps, and technical training. Let's bring your digital ideas to life!",
    category: "virtual",
    skills: ["React", "Node.js", "Python", "Mobile Development", "Technical Training"],
    location: "Kissy",
    ethnicity: "West African",
    rating: 4.8,
    reviewCount: 45,
    yearsExperience: 6,
    availability: "Mon-Fri, 8AM-5PM GMT",
    languages: ["English", "Twi", "French"],
    verified: true,
    age: 26,
    bodyType: "Athletic",
    interests: ["Beach", "Reading", "Photography"],
    isOnline: false,
    isLive: false,
    services: [
      { name: "Website Development", description: "Custom website from scratch", price: 2000, duration: "3-4 weeks" },
      { name: "Mobile App Development", description: "iOS/Android app development", price: 5000, duration: "6-8 weeks" },
      { name: "Code Review", description: "Detailed code review and recommendations", price: 150, duration: "2-3 days" },
      { name: "1-on-1 Tech Tutoring", description: "Personalized coding lessons", price: 80, duration: "1 hour" },
    ],
    portfolio: [
      { imageUrl: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", title: "E-learning Platform", description: "Built for 10k+ students" },
      { imageUrl: "/girls/1763046071553edited-image.webp", title: "Fintech App", description: "Mobile payment solution" },
      { imageUrl: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", title: "Tech Workshop", description: "Women in Tech bootcamp" },
    ],
    reviews: [
      { reviewerName: "Grace O.", reviewerAvatar: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", rating: 5, comment: "Nneka built our company website and it exceeded all expectations. Highly professional!", reviewedAt: "2024-01-25" },
    ],
  },
  {
    slug: "sofia",
    name: "Sofia Martinez",
    title: "Makeup Artist & Beauty Educator",
    avatar: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg",
    coverImage: "/girls/1774305302779edited-image.webp",
    bio: "Celebrity makeup artist with a passion for enhancing natural beauty. From bridal looks to editorial shoots, I create stunning transformations while teaching clients to feel confident in their own skin.",
    category: "companions",
    skills: ["Bridal Makeup", "Editorial", "Special Effects", "Skincare", "Beauty Workshops"],
    location: "Freetown",
    ethnicity: "West African",
    rating: 4.9,
    reviewCount: 203,
    yearsExperience: 9,
    availability: "Tue-Sun, 7AM-8PM",
    languages: ["Spanish", "English", "Portuguese"],
    verified: true,
    age: 32,
    bodyType: "Curvy",
    interests: ["Shopping", "Gaming", "Movies", "Swimming"],
    isOnline: true,
    isLive: false,
    services: [
      { name: "Bridal Package", description: "Trial + wedding day makeup", price: 400, duration: "Trial + Event" },
      { name: "Special Event Makeup", description: "Glam makeup for any occasion", price: 150, duration: "1-1.5 hours" },
      { name: "Makeup Lesson", description: "Personalized makeup tutorial", price: 120, duration: "2 hours" },
      { name: "Editorial/Photoshoot", description: "Professional makeup for shoots", price: 250, duration: "Half day" },
    ],
    portfolio: [
      { imageUrl: "/girls/1763046071553edited-image.webp", title: "Bridal Beauty", description: "Natural bridal glow" },
      { imageUrl: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", title: "Editorial Look", description: "Magazine cover shoot" },
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "Glam Transformation", description: "Evening glam look" },
    ],
    reviews: [
      { reviewerName: "Ana G.", reviewerAvatar: "/girls/1770314038130edited-image.webp", rating: 5, comment: "Sofia made me feel like a princess on my wedding day. My makeup lasted 12+ hours!", reviewedAt: "2024-01-08" },
    ],
  },
  {
    slug: "aiko",
    name: "Dr. Aiko Tanaka",
    title: "Physical Therapist & Movement Specialist",
    avatar: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg",
    coverImage: "/girls/1775215902622edited-image.webp",
    bio: "Helping people move better and live pain-free. I combine traditional physical therapy with yoga and pilates to create holistic treatment plans that address the root cause of movement issues.",
    category: "wellness",
    skills: ["Physical Therapy", "Sports Rehabilitation", "Yoga Therapy", "Pilates", "Pain Management"],
    location: "Hill Station",
    ethnicity: "African",
    rating: 4.8,
    reviewCount: 112,
    yearsExperience: 11,
    availability: "Mon-Sat, 9AM-6PM JST",
    languages: ["Japanese", "English"],
    verified: true,
    age: 22,
    bodyType: "Athletic",
    interests: ["Travel", "Art", "Hiking", "Photography"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Initial Assessment", description: "Comprehensive movement assessment", price: 180, duration: "1.5 hours" },
      { name: "Treatment Session", description: "Hands-on therapy session", price: 120, duration: "1 hour" },
      { name: "Online Consultation", description: "Virtual assessment and exercise plan", price: 80, duration: "45 mins" },
      { name: "Recovery Package", description: "8-session treatment program", price: 800, duration: "8 sessions" },
    ],
    portfolio: [
      { imageUrl: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", title: "Movement Therapy", description: "Functional movement training" },
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "Yoga Therapy", description: "Therapeutic yoga session" },
    ],
    reviews: [
      { reviewerName: "Keiko S.", reviewerAvatar: "/girls/1774305302779edited-image.webp", rating: 5, comment: "After years of back pain, Dr. Tanaka finally helped me find relief. Life-changing!", reviewedAt: "2024-01-19" },
    ],
  },
  {
    slug: "zara",
    name: "Zara Williams",
    title: "Professional Photographer & Visual Storyteller",
    avatar: "/girls/1774305302779edited-image.webp",
    coverImage: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg",
    bio: "Capturing authentic moments and telling compelling visual stories. I specialize in portrait photography, brand content, and documentary-style event coverage that brings out the true essence of my subjects.",
    category: "content-creators",
    skills: ["Portrait Photography", "Brand Photography", "Event Coverage", "Photo Editing", "Visual Direction"],
    location: "Wilberforce",
    ethnicity: "West African",
    rating: 4.9,
    reviewCount: 94,
    yearsExperience: 8,
    availability: "Mon-Fri, 8AM-6PM GMT",
    languages: ["English", "French"],
    verified: true,
    age: 31,
    bodyType: "Average",
    interests: ["Cooking", "Swimming", "Beach", "Photography", "Fitness"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Portrait Session", description: "1-hour portrait shoot with editing", price: 350, duration: "1-2 hours" },
      { name: "Brand Content Package", description: "Half-day shoot for business content", price: 800, duration: "4 hours" },
      { name: "Event Coverage", description: "Full event photography", price: 1200, duration: "Full day" },
      { name: "Headshot Session", description: "Professional headshots", price: 200, duration: "30 mins" },
    ],
    portfolio: [
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "Portrait Work", description: "Editorial portrait session" },
      { imageUrl: "/girls/1774305302779edited-image.webp", title: "Event Photography", description: "Corporate conference coverage" },
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Brand Content", description: "Product lifestyle shoot" },
    ],
    reviews: [
      { reviewerName: "Emma P.", reviewerAvatar: "/girls/1775215902622edited-image.webp", rating: 5, comment: "Zara captured our brand perfectly. The photos have elevated our entire marketing!", reviewedAt: "2024-01-14" },
    ],
  },
  {
    slug: "linda",
    name: "Linda Osei",
    title: "Professional Organizer & Home Stylist",
    avatar: "/girls/1775215902622edited-image.webp",
    coverImage: "/girls/1770314038130edited-image.webp",
    bio: "Transform your space, transform your life! I help busy professionals declutter, organize, and style their homes for maximum productivity and peace. Marie Kondo certified with a unique African aesthetic touch.",
    category: "entertainers",
    skills: ["Home Organization", "Decluttering", "Interior Styling", "Space Planning", "Closet Design"],
    location: "Bo",
    ethnicity: "West African",
    rating: 4.7,
    reviewCount: 68,
    yearsExperience: 5,
    availability: "Mon-Sat, 8AM-5PM EAT",
    languages: ["English", "Swahili"],
    verified: true,
    age: 25,
    bodyType: "Curvy",
    interests: ["Reading", "Gaming", "Music", "Art", "Fitness"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Room Makeover", description: "Complete room organization and styling", price: 250, duration: "4-6 hours" },
      { name: "Whole Home Package", description: "Full home organization", price: 800, duration: "2-3 days" },
      { name: "Virtual Consultation", description: "Online organizing session", price: 75, duration: "1 hour" },
      { name: "Closet Overhaul", description: "Wardrobe organization and styling", price: 180, duration: "3-4 hours" },
    ],
    portfolio: [
      { imageUrl: "/girls/1774305302779edited-image.webp", title: "Bedroom Makeover", description: "Before and after transformation" },
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Living Space", description: "Minimalist styling" },
      { imageUrl: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", title: "Closet Design", description: "Custom closet organization" },
    ],
    reviews: [
      { reviewerName: "Patricia M.", reviewerAvatar: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", rating: 5, comment: "Linda transformed my chaotic home into a peaceful sanctuary. Worth every penny!", reviewedAt: "2024-01-16" },
    ],
  },
  {
    slug: "carmen",
    name: "Carmen Reyes",
    title: "Immigration Lawyer & Legal Consultant",
    avatar: "/girls/1775215902622edited-image.webp",
    coverImage: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg",
    bio: "Navigating immigration law with compassion and expertise. I help individuals and families achieve their immigration goals, from visas to citizenship. Fluent in multiple languages to serve diverse communities.",
    category: "escorts",
    skills: ["Immigration Law", "Visa Applications", "Citizenship", "Legal Documentation", "Consultation"],
    location: "Lumley",
    ethnicity: "Sierra Leonean",
    rating: 4.8,
    reviewCount: 156,
    yearsExperience: 12,
    availability: "Mon-Fri, 9AM-5PM PST",
    languages: ["English", "Spanish", "Portuguese"],
    verified: true,
    age: 28,
    bodyType: "Curvy",
    interests: ["Art", "Nightlife", "Travel", "Hiking", "Movies", "Reading"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Initial Consultation", description: "Case assessment and strategy", price: 200, duration: "1 hour" },
      { name: "Visa Application", description: "Complete visa application service", price: 1500, duration: "Varies" },
      { name: "Green Card Process", description: "Full green card application", price: 3500, duration: "Varies" },
      { name: "Document Review", description: "Legal document review", price: 150, duration: "2-3 days" },
    ],
    portfolio: [
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Legal Services", description: "Comprehensive case management" },
      { imageUrl: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", title: "Client Success", description: "Citizenship ceremony" },
    ],
    reviews: [
      { reviewerName: "Maria L.", reviewerAvatar: "/girls/1763046071553edited-image.webp", rating: 5, comment: "Carmen made the immigration process so much less stressful. She got my family through!", reviewedAt: "2024-01-21" },
    ],
  },
  {
    slug: "suki",
    name: "Suki Park",
    title: "Data Analyst & Business Intelligence Specialist",
    avatar: "/girls/1763046071553edited-image.webp",
    coverImage: "/girls/1770314038130edited-image.webp",
    bio: "Turning data into actionable insights that drive business growth. I help companies make data-driven decisions through custom dashboards, analysis, and reporting that tells the story behind the numbers.",
    category: "virtual",
    skills: ["Data Analysis", "SQL", "Python", "Tableau", "Business Intelligence"],
    location: "Freetown",
    ethnicity: "Sierra Leonean",
    rating: 4.9,
    reviewCount: 52,
    yearsExperience: 7,
    availability: "Mon-Fri, 9AM-6PM KST",
    languages: ["Korean", "English", "Japanese"],
    verified: true,
    age: 29,
    bodyType: "Thick",
    interests: ["Nightlife", "Fashion", "Fitness"],
    isOnline: true,
    isLive: false,
    services: [
      { name: "Data Analysis Project", description: "Custom analysis and report", price: 1000, duration: "1-2 weeks" },
      { name: "Dashboard Creation", description: "Interactive business dashboard", price: 1500, duration: "2 weeks" },
      { name: "Data Consultation", description: "Strategy session for data needs", price: 150, duration: "1 hour" },
      { name: "Training Session", description: "Team training on analytics tools", price: 500, duration: "Half day" },
    ],
    portfolio: [
      { imageUrl: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", title: "Sales Dashboard", description: "Real-time sales analytics" },
      { imageUrl: "/girls/1763046071553edited-image.webp", title: "Market Analysis", description: "Competitor analysis report" },
    ],
    reviews: [
      { reviewerName: "James C.", reviewerAvatar: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", rating: 5, comment: "Suki's dashboard helped us identify growth opportunities we'd been missing for years.", reviewedAt: "2024-01-23" },
    ],
  },
  {
    slug: "blessing",
    name: "Blessing Nwosu",
    title: "Nail Artist & Salon Owner",
    avatar: "/girls/1774305302779edited-image.webp",
    coverImage: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg",
    bio: "Creating wearable nail art that expresses your unique personality! From classic manicures to elaborate 3D designs, I bring creativity and precision to every set. Your nails are my canvas.",
    category: "companions",
    skills: ["Nail Art", "Acrylics", "Gel Extensions", "3D Nail Design", "Nail Care"],
    location: "Bo",
    ethnicity: "Sierra Leonean",
    rating: 4.8,
    reviewCount: 187,
    yearsExperience: 6,
    availability: "Tue-Sat, 10AM-7PM EST",
    languages: ["English", "Igbo"],
    verified: true,
    age: 31,
    bodyType: "Slim",
    interests: ["Shopping", "Gaming", "Music"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Classic Manicure", description: "Basic nail care and polish", price: 35, duration: "45 mins" },
      { name: "Gel Full Set", description: "Full gel nail extensions", price: 80, duration: "1.5 hours" },
      { name: "Custom Nail Art", description: "Hand-painted designs", price: 120, duration: "2 hours" },
      { name: "3D Luxury Set", description: "Premium 3D nail art set", price: 200, duration: "3 hours" },
    ],
    portfolio: [
      { imageUrl: "/girls/1763046071553edited-image.webp", title: "Abstract Art", description: "Custom abstract nail design" },
      { imageUrl: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", title: "French Tips", description: "Modern French manicure" },
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "3D Flowers", description: "3D floral nail art" },
    ],
    reviews: [
      { reviewerName: "Tanya B.", reviewerAvatar: "/girls/1770314038130edited-image.webp", rating: 5, comment: "Blessing is a true artist! My nails always get so many compliments.", reviewedAt: "2024-01-17" },
    ],
  },
  {
    slug: "nadia",
    name: "Nadia Hassan",
    title: "Certified Doula & Birth Educator",
    avatar: "/girls/1774305302779edited-image.webp",
    coverImage: "/girls/1770314038130edited-image.webp",
    bio: "Supporting mothers through the beautiful journey of pregnancy and birth. As a certified doula with training in both modern and traditional practices, I provide emotional, physical, and educational support for expecting families.",
    category: "wellness",
    skills: ["Birth Support", "Prenatal Education", "Postpartum Care", "Lactation Support", "Childbirth Classes"],
    location: "Freetown",
    ethnicity: "Sierra Leonean",
    rating: 5,
    reviewCount: 73,
    yearsExperience: 9,
    availability: "On-call for births, appointments Mon-Fri",
    languages: ["English", "Arabic", "Farsi"],
    verified: true,
    age: 23,
    bodyType: "Average",
    interests: ["Fitness", "Cooking", "Art"],
    isOnline: true,
    isLive: true,
    services: [
      { name: "Birth Doula Package", description: "Prenatal visits + birth support + postpartum visit", price: 1500, duration: "Full service" },
      { name: "Postpartum Support", description: "In-home postpartum assistance", price: 45, duration: "Per hour" },
      { name: "Childbirth Education", description: "4-week childbirth preparation course", price: 350, duration: "4 weeks" },
      { name: "Virtual Consultation", description: "Online support session", price: 80, duration: "1 hour" },
    ],
    portfolio: [
      { imageUrl: "/girls/1768473640265545be2ef-480b-4043-98d2-45a614ad12fa.webp", title: "Birth Support", description: "Supporting families through birth" },
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "Education Classes", description: "Childbirth preparation workshop" },
    ],
    reviews: [
      { reviewerName: "Rachel K.", reviewerAvatar: "/girls/1774305302779edited-image.webp", rating: 5, comment: "Nadia was my rock during labor. I couldn't have done it without her calm presence.", reviewedAt: "2024-01-11" },
    ],
  },
  {
    slug: "victoria",
    name: "Victoria Santos",
    title: "Event Planner & Wedding Coordinator",
    avatar: "/girls/1775215902622edited-image.webp",
    coverImage: "/girls/1774305302779edited-image.webp",
    bio: "Creating unforgettable celebrations that reflect your unique story. From intimate gatherings to grand weddings, I handle every detail so you can enjoy your special day stress-free.",
    category: "entertainers",
    skills: ["Wedding Planning", "Event Design", "Vendor Management", "Budget Planning", "Day-of Coordination"],
    location: "Pujehun",
    ethnicity: "West African",
    rating: 4.9,
    reviewCount: 89,
    yearsExperience: 8,
    availability: "Mon-Sat, Flexible",
    languages: ["English", "Filipino", "Spanish"],
    verified: true,
    age: 32,
    bodyType: "Slim",
    interests: ["Movies", "Photography", "Music", "Hiking", "Cooking", "Fashion"],
    isOnline: true,
    isLive: false,
    services: [
      { name: "Full Wedding Planning", description: "Complete wedding planning service", price: 3500, duration: "6-12 months" },
      { name: "Day-of Coordination", description: "Wedding day management", price: 800, duration: "Event day" },
      { name: "Event Planning", description: "Corporate or private event planning", price: 1500, duration: "Varies" },
      { name: "Consultation", description: "Planning advice session", price: 100, duration: "2 hours" },
    ],
    portfolio: [
      { imageUrl: "/girls/1770314038130edited-image.webp", title: "Beach Wedding", description: "Destination wedding" },
      { imageUrl: "/girls/1774305302779edited-image.webp", title: "Garden Reception", description: "Elegant outdoor celebration" },
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Corporate Gala", description: "Annual company event" },
    ],
    reviews: [
      { reviewerName: "Andrea M.", reviewerAvatar: "/girls/1775215902622edited-image.webp", rating: 5, comment: "Victoria planned our dream wedding perfectly. Every detail was flawless!", reviewedAt: "2024-01-13" },
    ],
  },
  {
    slug: "amina",
    name: "Dr. Amina Bakare",
    title: "Online Tutor & Education Consultant",
    avatar: "/girls/1775215902622edited-image.webp",
    coverImage: "/girls/1774305302779edited-image.webp",
    bio: "Empowering students to reach their academic potential. PhD in Education with 14 years of teaching experience across all levels. Specializing in STEM subjects and test preparation for international exams.",
    category: "escorts",
    skills: ["Math Tutoring", "Science Tutoring", "Test Prep", "Academic Coaching", "Curriculum Development"],
    location: "Freetown",
    ethnicity: "African",
    rating: 4.9,
    reviewCount: 234,
    yearsExperience: 14,
    availability: "Mon-Sat, Flexible across time zones",
    languages: ["English", "Yoruba", "French"],
    verified: true,
    age: 22,
    bodyType: "Curvy",
    interests: ["Yoga", "Art", "Movies", "Shopping", "Swimming", "Reading"],
    isOnline: true,
    isLive: false,
    services: [
      { name: "1-on-1 Tutoring", description: "Personalized online tutoring session", price: 60, duration: "1 hour" },
      { name: "SAT/ACT Prep Package", description: "10-session test preparation", price: 500, duration: "10 sessions" },
      { name: "Academic Assessment", description: "Learning style and skills evaluation", price: 150, duration: "2 hours" },
      { name: "Group Classes", description: "Small group tutoring (3-5 students)", price: 35, duration: "1 hour/student" },
    ],
    portfolio: [
      { imageUrl: "/girls/1774305302779edited-image.webp", title: "Online Teaching", description: "Interactive virtual classroom" },
      { imageUrl: "/girls/1775215902622edited-image.webp", title: "Study Materials", description: "Custom learning resources" },
    ],
    reviews: [
      { reviewerName: "John P.", reviewerAvatar: "/girls/1730729028885E51555CF-B4F1-4993-B4CC-296E5C32DDBA.jpeg", rating: 5, comment: "Dr. Bakare helped my daughter improve her SAT score by 200 points! Incredible teacher.", reviewedAt: "2024-01-24" },
    ],
  },
];

// Idempotent seed — run via: npx convex run seed:seedProfessionals
export const seedProfessionals = mutation({
  args: {},
  handler: async (ctx) => {
    const passwordHash = await hashPassword("dodo123");
    const now = Date.now();
    const results: string[] = [];

    for (const pro of PROFESSIONALS) {
      const email = `${pro.slug}@dodo.pro`;

      // Skip if already exists (idempotent)
      const existing = await ctx.db
        .query("users")
        .withIndex("by_email", (q) => q.eq("email", email))
        .unique();

      if (existing) {
        results.push(`SKIP  ${pro.name}`);
        continue;
      }

      const startingPrice = Math.min(...pro.services.map((s) => s.price));

      const userId = await ctx.db.insert("users", {
        name: pro.name,
        email,
        passwordHash,
        isProfessional: true,
        avatarUrl: pro.avatar,
        coverImageUrl: pro.coverImage,
        title: pro.title,
        bio: pro.bio,
        category: pro.category,
        skills: pro.skills,
        location: pro.location,
        ethnicity: pro.ethnicity,
        rating: pro.rating,
        reviewCount: pro.reviewCount,
        yearsExperience: pro.yearsExperience,
        availability: pro.availability,
        languages: pro.languages,
        verified: pro.verified,
        age: pro.age,
        bodyType: pro.bodyType,
        interests: pro.interests,
        isOnline: pro.isOnline,
        isLive: pro.isLive,
        startingPrice,
        createdAt: now,
        updatedAt: now,
      });

      // Insert services
      for (const svc of pro.services) {
        await ctx.db.insert("professionalServices", {
          providerId: userId,
          name: svc.name,
          description: svc.description,
          price: svc.price,
          duration: svc.duration,
          createdAt: now,
        });
      }

      // Insert portfolio
      for (const item of pro.portfolio) {
        await ctx.db.insert("portfolio", {
          userId,
          imageUrl: item.imageUrl,
          title: item.title,
          description: item.description,
          createdAt: now,
        });
      }

      // Insert reviews
      for (const rev of pro.reviews) {
        await ctx.db.insert("professionalReviews", {
          providerId: userId,
          reviewerName: rev.reviewerName,
          reviewerAvatar: rev.reviewerAvatar,
          rating: rev.rating,
          comment: rev.comment,
          reviewedAt: rev.reviewedAt,
          createdAt: now,
        });
      }

      results.push(`ADDED ${pro.name} (${userId})`);
    }

    return results;
  },
});
